Merge dev into staging
USGS-WiM/NSS pull request #122
Opened 2020-02-21 15:02 UTC by kjacobsen16

- Issues #90, #91, #92, #105, #108, #110, #113, #115, #116

2020-02-21 15:13 UTC, harper-wavra requested changes
Undo these changes to remove Login button for staging.

2020-02-21 15:24 UTC, kjacobsen16 commented on src/app/app.component.html
> +            <a (click)="showLoginModal()" [class.hidden]="isLoggedIn">
```suggestion
            <!-- a (click)="showLoginModal()" [class.hidden]="isLoggedIn">
```

2020-02-21 15:24 UTC, kjacobsen16 commented on src/app/app.component.html
> +            </a>
```suggestion
            </a> -->
```

2020-02-26 18:48 UTC, harper-wavra approved these changes

2020-02-26 18:48 UTC, merged