Fixes #89
USGS-WiM/NSS pull request #192
Opened 2020-05-13 15:51 UTC by harper-wavra

2020-05-18 16:39 UTC, kjacobsen16 requested changes
I left a few comments on code changes. Most of them are small. I do think we should include the citation url somehow, maybe just do something similar to the mainview component, where the citation title/author text is a clickable link that opens in a new tab.

Otherwise I think this works well for now, but I'm going to make issues for some enhancements to it, both of which rely partially on changes coming through with issue 102 (still awaiting on re-projecting polygons sorry!)

2020-05-18 16:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.html
> +    <div style="padding-left: 20px; padding-right: 20px; padding-bottom: 20px;">
Generally, it's best not to have in-line styling. Try pulling these out into a class.

2020-05-18 16:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.html
> +    <div style="padding-top: 20px;">
Same as above, should be a class

2020-05-18 16:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.html
> -    <div class="modal-body">
I'm not sure why this was removed, but I believe the `modal-body` class has some padding, so this would fix some of the comments below.

2020-05-18 16:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.html
> -        </div>
I would put this back in to keep the format of our modals the same.

2020-05-18 16:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.css
> +.disabled-button{
I wouldn't call this `disabled-button` since you set it up for an `<i>` tag, not a `<button>`. Maybe just `disabled` or `disabled-icon`.

2020-05-18 16:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.css
> +    pointer-events: none;
I would change this to `cursor: not-allowed !important;`. That will show the no-entry sign when you hover over it.

2020-05-18 16:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.html
> +                    </div>
Instead of repeating things, you can have one `<i>` tag, but make certain properties conditional. In this case, you can set the click using `(click)="!l.regressionRegions?.length>0 && deleteCitation(l.id)"`.

You can also set conditional items using square brackets. For this item, you can do `[class.disabled-button]="l.regressionRegions?.length>0", which will only assign the disabled class if that statement is true.

Another way to set conditional statements is using the ternary/conditional operator: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator. This is not applicable to this part of the code, but is definitely useful for setting conditions in the html or js. I use it a lot.

2020-05-18 16:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.ts
> +                if(this.filterText){
This is a minor thing, so no need to change it but I usually try to put spaces after if statements and before `{`, so it would be `if (this.filterText) {`. I try to keep the code formatting consistent.

2020-05-18 16:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.ts
> +            if(title.includes(input))
We should check the author name as well

2020-05-18 16:44 UTC, kjacobsen16 commented
I'm also rethinking the columns now - "Title and Author" should maybe just be something like "Citation" or "Citation Info". And we should somehow make the title and authors more visibly separate. Maybe play with some bolding or italics? Or pulling out to separate columns?

2020-05-18 18:06 UTC, harper-wavra commented
I made the authors in italics, I thought the bold was kind of a lot to look at. Let me know if you think something different would look better.

2020-05-18 19:39 UTC, kjacobsen16 requested changes
I think I reviewed too quickly before and missed a couple edits - sorry about that! Again, mostly just some code enhancements.

2020-05-18 19:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.html
> +    <div class="modalbody; table">
The class name should be `modal-body` with a hyphen, then you can probably remove the table class. Also, usually the way multiple classes are applied is by putting a space with no semi-colon.

2020-05-18 19:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.html
> +                        <i title="Delete Citation" (click)="deleteCitation(l.id)" class="fa fa-times" [class.disabled-icon]="l.regressionRegions?.length>0" aria-hidden="true" style="cursor:pointer"><
This is missing the conditional portion I mentioned before. You can still click delete if the icon has the disabled class since it's just affected the css. The (click) should say something like `(click)="!l.regressionRegions?.length>0 && deleteCitation(l.id)"` so it'll only run the click function if there are no regression regions.

2020-05-18 19:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.html
>                          <div>{{l.title}}</div>
I missed this before, but in the mainview the author is listed before the title, maybe we should do it that way to keep it consistent.

2020-05-18 19:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.ts
> +            let author = item.author.toLowerCase();
Can we also check the regression regions? It'll be a little trickier, but you can still have it on one line as I suggested above by using another filter on the regression regions and checking the length of what's returned. Try to get this working for a bit. If you get stuck, let me know and I'll point you in the right direction.

2020-05-18 19:39 UTC, kjacobsen16 commented on src/app/shared/components/managecitations/managecitations.component.ts
> +        this.filteredData = this.citations.filter((item)=>{
I must've rushed this the first time. Filters are nice in that you can just put the conditions in there without needing all the fluff. You can do this in one line. Here's a much simpler way to do this:
```
this.filteredData = this.citations.filter((item)=>
            item.author.toLowerCase().includes(input.toLowerCase()) || 
            item.title.toLowerCase().includes(input.toLowerCase()));
```

2020-05-21 13:48 UTC, kjacobsen16 approved these changes
Looks great!

2020-05-21 13:49 UTC, merged