Fixes #162
USGS-WiM/NSS pull request #215
Opened 2020-06-11 16:25 UTC by harper-wavra

Able to assign existing citations when adding/editing regression regions.

2020-06-11 19:18 UTC, harper-wavra commented
I think this is working now. You are able to assign existing citations when adding/editing regression regions. I fixed the issue with editing an existing regression region, removing the citation, then adding an existing citation. Also set the `citationID` to `currentCitation.id` so it is no longer creating a new citation each time. 

When using an existing citation I made the input read only so a citation would not accidentally get edited for all of its associated regression regions. I think it would be better to have the "edit citation" option inside the mange citation modal that way it is clear when you edit that citation it will be edited for all the regression regions that use that citation instead of just the one you are working on in the edit/add regression region modal. Let me know what you think.

2020-06-12 13:29 UTC, kjacobsen16 commented
I think that's a great idea! Go ahead and add an issue for that. If you do that, you can also remove the edit button next to the citations in the main edit scenario page I think.

2020-06-12 14:13 UTC, kjacobsen16 requested changes
It's working well, I just made some code cleanup/improvement suggestions.

2020-06-12 14:13 UTC, kjacobsen16 commented on src/app/shared/components/addregressionregion/addregressionregion.component.ts
> +import { __core_private_testing_placeholder__ } from '@angular/core/testing';
Looks like an accidental import

2020-06-12 14:13 UTC, kjacobsen16 commented on src/app/shared/components/addregressionregion/addregressionregion.component.ts
> +          this.rr = result.regRegionID
tiny issue but this is missing a `;`

2020-06-12 14:13 UTC, kjacobsen16 commented on src/app/shared/components/addregressionregion/addregressionregion.component.ts
> +      this.currentCitation = item
Also missing `;`

2020-06-12 14:13 UTC, kjacobsen16 commented on src/app/shared/components/addregressionregion/addregressionregion.component.ts
> +          }
One of these `if`s is unnecessary. You could just do `if (this.addCitation && this.newCitation == true)` on line 321 and cut lines 322 and 324-327, since adding an existing citation just involves editing the citationID, not creating a new citation. That way it'll just do the regular stuff (cancelCreateRegression, requeryFilters) if you're not creating a _new_ citation.

2020-06-12 14:13 UTC, kjacobsen16 commented on src/app/shared/components/addregressionregion/addregressionregion.component.ts
> +              }
Same here, this can be shortened by doing 
```
} else if (this.addCitation && this.newCitation == true) {
  this.createNewCitation(this.selectedRegRegion);
}
```

2020-06-12 14:13 UTC, kjacobsen16 commented on src/app/shared/components/addregressionregion/addregressionregion.component.ts
> +    this.saveFilters();
The tabbing in this function is off

2020-06-12 14:13 UTC, kjacobsen16 commented on src/app/shared/components/addregressionregion/addregressionregion.component.ts
> +        this.newCitForm.controls['citationURL'].setValue(null);
Resetting the `newCitForm` (line 410) should reset all the controls in it, so this isn't needed.

2020-06-12 14:13 UTC, kjacobsen16 commented on src/app/shared/components/addregressionregion/addregressionregion.component.ts
> +      this.newCitation = true
Missing `;`

2020-06-12 14:13 UTC, kjacobsen16 commented on src/app/shared/services/app.service.ts
> +    }
This all works well, but could probably be combined with the showManageCitations modal stuff, similarly to how we're sending things along to the showHideAddRegressionRegion modal, so you're only setting one subject when you want the modal shown.

2020-06-15 14:03 UTC, kjacobsen16 approved these changes
Working well!

2020-06-15 14:03 UTC, kjacobsen16 commented on src/app/shared/components/addregressionregion/addregressionregion.component.ts
> +                });
If we're not editing the citation properties in the regression region component, then this won't be needed anymore. We can leave it in for now while we're waiting to get the new method working, but something to think about.

2020-06-15 14:05 UTC, merged