Fixes #263
USGS-WiM/NSS pull request #381
Opened 2020-12-04 21:05 UTC by harper-wavra

I made it so it works sort of like the editing of gages. The edit limitations section is sort of its own section and the changes made to the limitations get saved right away. 

Files editied:
addregressionregion.component.html - added limitations form and spacing
addregressionregion.component.scss - added table styling
addregressionregion.component.ts - limitation code and organized into sections
managecitations.component.html - spacing
managecitations.component.ts - remove console.log
app.service.ts - spacing
config - added limitations URL

2020-12-11 21:16 UTC, kjacobsen16 requested changes
Overall, looking good! Thanks for the breakdown of your changes, that saved me some time. A couple notes that can wait until the rest of the non-management side issues are fixed:
- [ ]  Can we limit the variable units for the limitations to the units assigned to the variable type, similarly to how we're limiting them now in the add scenario modal?
- [ ] I think I deleted a limitation and it deleted before I hit save.. Can you double check that and make sure all changes are going through after the user saves the regression region?
- [x] While we're in the add regression region modal, can you make the "Method" field optional for now (if possible)? and also move the "Code" input up to the top, before Status?

2020-12-11 21:16 UTC, kjacobsen16 commented on src/app/shared/components/addregressionregion/addregressionregion.component.ts
> +    });
Is this how we update items in the add scenario modal? I wonder if there's a better way to do this by linking the html directly with it? If it looks like a long task, we could maybe add it to #206 (which I haven't looked at in a while)

2020-12-11 21:16 UTC, kjacobsen16 commented on src/app/shared/components/addregressionregion/addregressionregion.component.ts
> +      this.createNewLimitation(this.newLimitation);
We might be able to tie the limitations in with the reg region form instead, then we wouldn't need to worry about storing these and adding them separately. I think the add scenario component does that with the parameters and errors?

2020-12-18 15:37 UTC, harper-wavra commented
This is in reply to your second comment. So I wasn't able to make all changes  go through after the user saves the regression region because there were too many things the user could add/edit/delete before saving. We have the citation and location saving after the user saves the regression region because they user can only save/edit/delete that one item. For the limitations however, the user can add/edit/delete each limitation and also add/edit/delete each variable within each limitation. So I made it work like it works when you are editing a gage. The limitations section is sort of its own section and the changes made to the limitations get saved right away. That is why I created that "Edit Limitations" button inside the regression modal to try and make it clear to the user your changes to limitations are getting saved right away.

2021-02-09 16:28 UTC, harper-wavra commented
Waiting on service issue https://github.com/USGS-WiM/NSSServices/issues/186(https://github.com/USGS-WiM/NSSServices/issues/186)

2021-02-09 16:28 UTC, closed without merging