Fixes #364
USGS-WiM/NSS pull request #383
Opened 2020-12-10 22:01 UTC by harper-wavra

- Display variables metricUnitTypeID and englishUnitTypeID in the settings page table and allow user to select both when adding/editing a variable type.
- Users are limited to selecting either the metric or english unit type when selecting the unit type for each scenario parameter in add scenario modal.
- Display the statistic group for each variable type in the settings page and allow the selection of a statistic group when adding/editing a variable type (only "BC" def type)
-  limit the statistic group selection in the add scenario modal to statistic groups with the "FS" def type
- displays and filters the statistic groups for the basin characteristics

Files Changes
- gagepage.component.html - added html to filter and show the characteristics statistic groups
- gagepage.component.ts - added code to filter and sort the characteristics into statistic groups
- variabletypes.component.html - displays english and metric unit type, allows user to select both when adding/editing a variable type
- variabletypes.component.ts - code to allow user to select english and metric unit type when adding/editing a variable type
- addscenario.component.html - display either the metric or english unit type when selecting the unit type for each scenario parameter
- addscenario.component.ts - code to limit users to selecting either the metric or english unit type when selecting the unit type for each scenario parameter
- not sure why the dist files changed

2020-12-11 22:37 UTC, kjacobsen16 requested changes
Great job, lots of important changes here. A few things:
1. When a new variable type for a parameter is changed, we should clear the unit associated with it in case the default units change.
2. The dropdown gets cut off when filtering the physical characteristics in the gage page - Mitch might be able to help here.
![image](https://user-images.githubusercontent.com/35497731/101956573-7146e600-3bc5-11eb-8f7a-66cc65859c1b.png)
3. This is my bad, but we should also limit the unit selection when adding characteristics in the gage page to the default variable types. Sorry about that!
4. Again, something I missed - can you display the DefType in the Statistic Groups Table in the Settings page and allow assigning the deftype when creating a new statistic group? Options should be "FS" (meaning Flow Statistics) or "BC" (meaning Basic Characteristics).

Feel free to make a separate issue for some of these.

2020-12-11 22:37 UTC, kjacobsen16 commented on src/app/shared/components/addscenario/addscenario.component.ts
> +                }
The whole MetricUnitType and EnglishUnitType are both included in the variables objects, so you don't actually need to look through the `this.unitTypes` object here at all, just add the two default units to the list (and check that the default unit IDs are different before adding the metric unit type)

2020-12-14 15:45 UTC, harper-wavra commented
I created new issues for the last two changes requested. @mitch-wim could you take a look at the physical characteristic "Filter by StatisticGroup" dropdown in the Gagepage (the second comment)? 50276000 is one gage that has this table.

2020-12-22 18:13 UTC, kjacobsen16 approved these changes
👍

2020-12-22 18:13 UTC, merged