Hw 435
USGS-WiM/NSS pull request #442
Opened 2021-03-11 19:40 UTC by harper-wavra

- For `stationChars` changed `isRegulated` to required.
- For `statChars` changed `yearsOfRecords` and `comments` to optional.
- For `charChars` changes `comments` to optional.
- Added function `checkForRequiredColumns`. Which if the headers for the batch upload have been populated it will create an array of required characteristics for each different type of upload. It will then sort that required array and the header row, compare them and find any missing required columns. If there are missing required columns it will print out an error, add to the `errorList`, and not let the user submit the data.
- Cleaned up file, spacing, missing ;, removed unused/duplicate function, removed console.logs.

2021-03-12 21:53 UTC, kjacobsen16 requested changes
Hm, I'm still able to hit the submit button when I'm (a) missing a required header (e.g. Longitude) or (b) have a gage that already exists.

2021-03-15 13:23 UTC, harper-wavra commented
Could you provide the steps you took when missing a required headers. I tried now and deleted the Longitude column and I am not able to submit the stations.
![image](https://user-images.githubusercontent.com/59063181/111159975-a87fb700-8567-11eb-90c7-928506a23e1a.png)

2021-03-15 18:09 UTC, kjacobsen16 commented
This is strange.. I can't replicate the issue at all, although I can see that the station went through without a longitude 🤷‍♀️ I have no idea how I did this.

I'll call it good since I can't replicate it, but we'll have to keep an eye out and make sure we document steps if this happens again.

2021-03-15 18:10 UTC, kjacobsen16 approved these changes

2021-03-15 18:10 UTC, merged